[project]
name = "coderama"
version = "0.1.1"
requires-python = ">=3.12"
dependencies = [
    "fastmcp==2.13.1",
    "ddgs==9.9.0",
    "googlesearch-python==1.3.0",
]

[project.scripts]
coderama = "main:main" 